export const COUNTRIES_REQUEST = 'COUNTRIES_REQUEST'
export const COUNTRIES_SUCCESS = 'COUNTRIES_SUCCESS'
export const COUNTRIES_FAIL = 'COUNTRIES_FAIL'

export const SELECT_COUNTRY = 'SELECT_COUNTRIY'
export const SELECT_COUNTRY_SUCCESS = 'SELECT_COUNTRY_SUCCESS'
export const RESET_COUNTRY = 'RESET_COUNTRY'

export const UPDATE_CONT_COUNTRY = 'UPDATE_CONT_COUNTRY'
export const RESET_CONT_COUNTRY = 'RESET_CONT_COUNTRY'
